### ISSUE TITLE
Demo sites: 6-classic.demo.plone.org

### ISSUE THREAD

**Issue by ericof** [plone/ai-team#1]
# Tasks
- [x] Update Nginx to respond to 6-classic.demo.plone.org
- [x] Create 6-classic.demo.plone.org on Cloudflare

**Comment by fulv** [comment]
Is `demo` the host?  https://github.com/plone/ai-team-private/blob/master/ansible/host_vars/demo.yml

**Comment by ericof** [comment]
Yes, but the server is managed by @pbauer. So, we will need his help to get this done :-)

**Comment by ericof** [comment]
Yes, but the server is managed by @pbauer. So, we will need his help to get this done :-)
